QLThucTap_INFOdation.App/Areas/Admin/Controllers/GUIs/EmailTemplatesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using Newtonsoft.Json;
using PagedList;
using QLThucTap_INFOdation.BusinessLogic.IService;
using QLThucTap_INFOdation.BusinessLogic.Service;
using Repository.DAL;
using Repository.Models;

namespace QLThucTap_INFOdation.App.Areas.Admin.Controllers.GUIs
{
    public class EmailTemplateController : Controller
    {
        // GET: ManagerMVC
        private readonly IUserPermissionService _userpermission;
        private InternContext db = new InternContext();
        string url = "http://localhost:54224/api/emailtemplateapi";
        HttpClient client;
        public EmailTemplateController()
        {
            _userpermission = new UserPermissionService();
            client = new HttpClient();
            client.BaseAddress = new Uri(url);
            client.DefaultRequestHeaders.Accept.Clear();
            client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
        }

        private bool IsHaveCreateEmailTemplate()
        {
            var findper = _userpermission.GetUserPermissionByUsername(Session["Username"].ToString());
            if (findper.Contains("Create Email Template") || findper.Contains("Full All Access") || findper.Contains("Full On Email Template"))
            {
                return true;
            }
            return false;
        }
        private bool IsHaveUpdateEmailTemplate()
        {
            var findper = _userpermission.GetUserPermissionByUsername(Session["Username"].ToString());
            if (findper.Contains("Update Email Template") || findper.Contains("Full All Access") || findper.Contains("Full On Email Template"))
            {
                return true;
            }
            return false;
        }
        private bool IsHaveReadEmailTemplate()
        {
            var findper = _userpermission.GetUserPermissionByUsername(Session["Username"].ToString());
            if (findper.Contains("Read Email Template") || findper.Contains("Full All Access") || findper.Contains("Full On Email Template"))
            {
                return true;
            }
            return false;
        }
        private bool IsHaveDeleteEmailTemplate()
        {
            var findper = _userpermission.GetUserPermissionByUsername(Session["Username"].ToString());
            if (findper.Contains("Delete Email Template") || findper.Contains("Full All Access") || findper.Contains("Full On Email Template"))
            {
                return true;
            }
            return false;
        }
        // GET: mvcusers
        //public async Task<ActionResult> Index()
        public ActionResult Index()
        {
            if (IsHaveReadEmailTemplate())
            {
                var lstmng = db.EmailTemplates.ToList<EmailTemplate>();
                return View(lstmng);
            }
            else
                return View("ErrorFunction");
        }

        // GET: mvcusers/Details/5
        public async Task<ActionResult> Details(int id)
        {
            if (IsHaveReadEmailTemplate())
            {
                HttpResponseMessage responseMessage = await client.GetAsync(url + "/" + id);
                if (responseMessage.IsSuccessStatusCode)
                {
                    var responseData = responseMessage.Content.ReadAsStringAsync().Result;
                    var usr = JsonConvert.DeserializeObject<EmailTemplate>(responseData);
                    return View(usr);
                }
            }

            return View("ErrorFunction");
        }
        // GET: mvcusers/Create
        public ActionResult Create()
        {
            if (IsHaveCreateEmailTemplate())
            {
                return View(new EmailTemplate());
            }
            else
                return View("ErrorFunction");
        }

        // POST: mvcusers/Create

        [HttpPost]
        public async Task<ActionResult> Create(EmailTemplate usr)
        {

            HttpResponseMessage responseMessage = await client.PostAsJsonAsync(url, usr);
            if (responseMessage.IsSuccessStatusCode)
            {
                return RedirectToAction("Index");
            }
            //return RedirectToAction("Error");
            ModelState.AddModelError(string.Empty, "Vui lòng điền đúng thông tin");

            return View(usr);
        }


        // GET: mvcusers/Edit/5
        public async Task<ActionResult> Edit(int id)
        {
            if (IsHaveUpdateEmailTemplate())
            {
                HttpResponseMessage responseMessage = await client.GetAsync(url + "/" + id);
                if (responseMessage.IsSuccessStatusCode)
                {
                    var responseData = responseMessage.Content.ReadAsStringAsync().Result;

                    var usr = JsonConvert.DeserializeObject<EmailTemplate>(responseData);

                    return View(usr);
                }
            }

            return View("ErrorFunction");
        }

        // POST: mvcusers/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        public async Task<ActionResult> Edit(int id, EmailTemplate usr)
        {

            HttpResponseMessage responseMessage = await client.PutAsJsonAsync(url + "/" + id, usr);
            if (responseMessage.IsSuccessStatusCode)
            {
                return RedirectToAction("Index");
            }
            //return RedirectToAction("Error");
            ModelState.AddModelError(string.Empty, "Vui lòng điền đúng thông tin");

            return View(usr);
        }

        public async Task<ActionResult> Delete(int id)
        {
            if (IsHaveDeleteEmailTemplate())
            {
                HttpResponseMessage responseMessage = await client.GetAsync(url + "/" + id);
                if (responseMessage.IsSuccessStatusCode)
                {
                    var responseData = responseMessage.Content.ReadAsStringAsync().Result;

                    var usr = JsonConvert.DeserializeObject<EmailTemplate>(responseData);

                    return View(usr);
                }
            }

            return View("ErrorFunction");
        }
        //The DELETE method
        [HttpPost]
        public async Task<ActionResult> Delete(int id, EmailTemplate usr)
        {

            HttpResponseMessage responseMessage = await client.DeleteAsync(url + "/" + id);
            if (responseMessage.IsSuccessStatusCode)
            {
                return RedirectToAction("Index");
            }
            return RedirectToAction("Error");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

QLThucTap_INFOdation.App/Areas/Admin/Views/EmailTemplate/Create.cshtml
@model Repository.Models.EmailTemplate

@{
    /**/

    ViewBag.Title = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_Layout1.cshtml";
}
@Html.AntiForgeryToken()
<!-- Content Header (Page header) -->
<section class="content-header">
    <h1>
        Email Template
    </h1>
</section>
<!-- Main content -->
<section class="content container-fluid">
    <!-- Horizontal Form -->
    <div class="box box-info">
        <div class="box-header with-border">
            <h3 class="box-title">Add Email Template</h3>
        </div>
        <!-- /.box-header -->
        <!-- form start -->
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <form class="form-horizontal" method="post" action="Create">
            <div class="box-body">
                <div class="form-group">
                    @Html.LabelFor(model => model.EmailFor, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.EmailFor, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.EmailFor, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Subject, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        <div class="checkbox">
                            @Html.EditorFor(model => model.Subject)
                            @Html.ValidationMessageFor(model => model.Subject, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.Body1, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        <div class="checkbox">
                            @Html.EditorFor(model => model.Body1)
                            @Html.ValidationMessageFor(model => model.Body1, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.Body2, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        <div class="checkbox">
                            @Html.EditorFor(model => model.Body2)
                            @Html.ValidationMessageFor(model => model.Body2, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.Body3, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        <div class="checkbox">
                            @Html.EditorFor(model => model.Body3)
                            @Html.ValidationMessageFor(model => model.Body3, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.Body4, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        <div class="checkbox">
                            @Html.EditorFor(model => model.Body4)
                            @Html.ValidationMessageFor(model => model.Body4, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>
            </div>
            <!-- /.box-body -->
            <div class="box-footer">
                <button onclick="JavascriptFunction();" type="submit" class="btn btn-info pull-right">Create</button>
            </div>
            <div>
                @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-info", onclick = "JavascriptFunction();" })
            </div>
            <!-- /.box-footer -->
        </form>
    </div>
    <!-- /.box -->
</section>
<div id="divLoading" style="margin: 0px; padding: 0px; position: fixed; right: 0px;
    top: 0px; width: 100%; height: 100%; background-color: #666666; z-index: 30001;
    opacity: .8; filter: alpha(opacity=70);display:none">
    <p style="position: absolute; top: 50%; left: 50%; color: White;">
        <img src="~/img/ajax-loader (1).gif"><br />Please Wait...
    </p>
</div>

<script type="text/javascript" language="javascript">
    function JavascriptFunction() {
        var url = '@Url.Action("Create", "EmailTemplate")';
        $("#divLoading").show();
        $.post(url, null,
                function (data) {
                    $("#PID")[0].innerHTML = data;
                    $("#divLoading").hide();
                });
    }
</script>

QLThucTap_INFOdation.App/Areas/Admin/Views/EmailTemplate/Delete.cshtml
@model Repository.Models.EmailTemplate

@{
    /**/

    ViewBag.Title = "Delete";
    Layout = "~/Areas/Admin/Views/Shared/_Layout1.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Email Template</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.id)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.id)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EmailFor)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EmailFor)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Subject)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Subject)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Body1)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Body1)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Body2)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Body2)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Body3)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Body3)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Body4)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Body4)
        </dd>        

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input onclick="JavascriptFunction();" type="submit" value="Delete" class="btn btn-danger" /> |
            @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-info", onclick = "JavascriptFunction();" })
        </div>
    }
</div>
<div id="divLoading" style="margin: 0px; padding: 0px; position: fixed; right: 0px;
    top: 0px; width: 100%; height: 100%; background-color: #666666; z-index: 30001;
    opacity: .8; filter: alpha(opacity=70);display:none">
    <p style="position: absolute; top: 50%; left: 50%; color: White;">
        <img src="~/img/ajax-loader (1).gif"><br />Please Wait...
    </p>
</div>

<script type="text/javascript" language="javascript">
    function JavascriptFunction() {
        var url = '@Url.Action("Delete", "TrainingManager")';
        $("#divLoading").show();
        $.post(url, null,
                function (data) {
                    $("#PID")[0].innerHTML = data;
                    $("#divLoading").hide();
                });
    }
</script>

QLThucTap_INFOdation.App/Areas/Admin/Views/EmailTemplate/Details.cshtml
@model Repository.Models.EmailTemplate
@{
    /**/

    ViewBag.Title = "Details";
    Layout = "~/Areas/Admin/Views/Shared/_Layout1.cshtml";
}


<h2>Details</h2>

<div>
    <h4>Email Template</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.id)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.id)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EmailFor)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EmailFor)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Subject)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Subject)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Body1)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Body1)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Body2)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Body2)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Body3)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Body3)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Body4)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Body4)
        </dd>
    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.id }, new { @class = "btn btn-info", onclick = "JavascriptFunction();" }) |
    @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-info", onclick = "JavascriptFunction();" })
</p>

<div id="divLoading" style="margin: 0px; padding: 0px; position: fixed; right: 0px;
    top: 0px; width: 100%; height: 100%; background-color: #666666; z-index: 30001;
    opacity: .8; filter: alpha(opacity=70);display:none">
    <p style="position: absolute; top: 50%; left: 50%; color: White;">
        <img src="~/img/ajax-loader (1).gif"><br />Please Wait...
    </p>
</div>

<script type="text/javascript" language="javascript">
    function JavascriptFunction() {
        var url = '@Url.Action("Details", "EmailTemplate")';
        $("#divLoading").show();
        $.post(url, null,
                function (data) {
                    $("#PID")[0].innerHTML = data;
                    $("#divLoading").hide();
                });
    }
</script>

QLThucTap_INFOdation.App/Areas/Admin/Views/EmailTemplate/Edit.cshtml
@model Repository.Models.EmailTemplate

@{
    /**/

    ViewBag.Title = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_Layout1.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>Email Template</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.id)
    <div class="form-group">
        @Html.LabelFor(model => model.EmailFor, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.EmailFor, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.EmailFor, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Subject, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Subject)
            @Html.ValidationMessageFor(model => model.Subject, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.Body1, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Body1, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Body1, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.Body2, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Body2, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Body2, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.Body3, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Body3, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Body3, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.Body4, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Body4, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Body4, "", new { @class = "text-danger" })
        </div>
    </div>



    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input onclick="JavascriptFunction();" type="submit" value="Save" class="btn btn-info" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-info", onclick = "JavascriptFunction();" })
</div>
<div id="divLoading" style="margin: 0px; padding: 0px; position: fixed; right: 0px;
    top: 0px; width: 100%; height: 100%; background-color: #666666; z-index: 30001;
    opacity: .8; filter: alpha(opacity=70);display:none">
    <p style="position: absolute; top: 50%; left: 50%; color: White;">
        <img src="~/img/ajax-loader (1).gif"><br />Please Wait...
    </p>
</div>

<script type="text/javascript" language="javascript">
    function JavascriptFunction() {
        var url = '@Url.Action("Edit", "EmailTemplate")';
        $("#divLoading").show();
        $.post(url, null,
                function (data) {
                    $("#PID")[0].innerHTML = data;
                    $("#divLoading").hide();
                });
    }
</script>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

QLThucTap_INFOdation.App/Areas/Admin/Views/EmailTemplate/Index.cshtml
@model IEnumerable<Repository.Models.EmailTemplate>
@{

    /**/

    ViewBag.Title = "List of Email Templates";
    Layout = "~/Areas/Admin/Views/Shared/_Layout1.cshtml";
}

<h2>Index</h2>
<p>
    @Html.ActionLink("Create New", "Create", null, new { @class = "btn btn-info",onclick = "JavascriptFunction();"})
</p>
<table id="emailtemplate" class="tableStyle1">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.EmailFor)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Subject)
            </th>
            <th></th>
        </tr>
    </thead>

    @foreach (var item in Model)
    {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.id)
        </td>

        <td>
            @Html.DisplayFor(modelItem => item.EmailFor)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Subject)
        </td>
        <td>
            @Html.ActionLink(" ", "Edit", new { id = item.id }, new { @class = "glyphicon glyphicon-edit", onclick = "JavascriptFunction();" })<br />@Html.ActionLink(" ", "Details", new { id = item.id }, new { @class = "glyphicon glyphicon-eye-open", onclick = "JavascriptFunction();" })<br/>@Html.ActionLink(" ", "Delete", new { id = item.id }, new { @class = "glyphicon glyphicon-trash", onclick = "JavascriptFunction();" })
        </td>
    </tr>
    }

</table>

<link href="/Content/DataTables/css/jquery.dataTables.min.css" rel="stylesheet" />

@section scripts
{
    <script src="/Scripts/DataTables/jquery.dataTables.min.js"></script>
    <script>
        $(document).ready(function () {
            $("#emailtemplate").DataTable();

        });
    </script>
    <style>
        td.highlight1 {
            background-color: #B961C3 !important;
        }

        .tableStyle1 {
            font-family: "Trebuchet MS", Arial, Helvetica, sans-serif;
            border-collapse: collapse;
            width: auto;
        }
            /*Style for Table Head - TH*/
            .tableStyle1 th {
                text-align: left;
                background-color: #8b1dba;
                color: #fff;
                text-align: left;
                padding: 25px;
            }
            /*TD and TH Style*/
            .tableStyle1 td, .tableStyle1 th {
                border: 1px solid #dedede; /*Border color*/
                padding: 15px;
            }
            /*Table Even Rows Styles*/
            .tableStyle1 tr:nth-child(even) {
                background-color: #EFF1F1;
            }
            /*Table ODD Rows Styles*/
            .tableStyle1 tr:nth-child(odd) {
                background-color: #E3EDED;
            }
            /*Table Row HOver Style*/
            .tableStyle1 tr:hover {
                background-color: #B961C3;
            }
    </style>
    <script>
        $(document).ready(function () {
            var table = $('#emailtemplate').DataTable();

            $('#emailtemplate tbody')
                .on('mouseenter', 'td', function () {
                    var colIdx = table.cell(this).index().column;

                    $(table.cells().nodes()).removeClass('highlight');
                    $(table.column(colIdx).nodes()).addClass('highlight');
                });
        });
    </script>
    <div id="divLoading" style="margin: 0px; padding: 0px; position: fixed; right: 0px;
    top: 0px; width: 100%; height: 100%; background-color: #666666; z-index: 30001;
    opacity: .8; filter: alpha(opacity=70);display:none">
        <p style="position: absolute; top: 50%; left: 50%; color: White;">
            <img src="~/img/ajax-loader (1).gif"><br />Please Wait...
        </p>
    </div>

    <script type="text/javascript" language="javascript">
    function JavascriptFunction() {
        var url = '@Url.Action("Index", "EmailTemplate")';
        $("#divLoading").show();
        $.post(url, null,
                function (data) {
                    $("#PID")[0].innerHTML = data;
                    $("#divLoading").hide();
                });
    }
    </script>
}