QLThucTap_INFOdation.App/Areas/Admin/Controllers/GUIs/TrainingManagersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Net.Mail;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using Newtonsoft.Json;
using PagedList;
using QLThucTap_INFOdation.BusinessLogic.IService;
using QLThucTap_INFOdation.BusinessLogic.Service;
using Repository.DAL;
using Repository.Models;

namespace QLThucTap_INFOdation.App.Areas.Admin.Controllers.GUIs
{
    public class TrainingManagerController : Controller
    {
        // GET: ManagerMVC
        private readonly IUserPermissionService _userpermission;
        private InternContext db = new InternContext();
        string url = "http://localhost:54224/api/trainingmanagerapi";
        HttpClient client;
        public TrainingManagerController()
        {
            _userpermission = new UserPermissionService();
            client = new HttpClient();
            client.BaseAddress = new Uri(url);
            client.DefaultRequestHeaders.Accept.Clear();
            client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
        }

        private bool IsHaveCreateTrainingManager()
        {
            var findper = _userpermission.GetUserPermissionByUsername(Session["Username"].ToString());
            if (findper.Contains("Create Training Manager") || findper.Contains("Full All Access") || findper.Contains("Full On Training Manager"))
            {
                return true;
            }
            return false;
        }
        private bool IsHaveUpdateTrainingManager()
        {
            var findper = _userpermission.GetUserPermissionByUsername(Session["Username"].ToString());
            if (findper.Contains("Update Training Manager") || findper.Contains("Full All Access") || findper.Contains("Full On Training Manager"))
            {
                return true;
            }
            return false;
        }
        private bool IsHaveReadTrainingManager()
        {
            var findper = _userpermission.GetUserPermissionByUsername(Session["Username"].ToString());
            if (findper.Contains("Read Training Manager") || findper.Contains("Full All Access") || findper.Contains("Full On Training Manager"))
            {
                return true;
            }
            return false;
        }
        private bool IsHaveDeleteTrainingManager()
        {
            var findper = _userpermission.GetUserPermissionByUsername(Session["Username"].ToString());
            if (findper.Contains("Delete Training Manager") || findper.Contains("Full All Access") || findper.Contains("Full On Training Manager"))
            {
                return true;
            }
            return false;
        }
        // GET: mvcusers
        //public async Task<ActionResult> Index()
        public ActionResult Index()
        {
            if (IsHaveReadTrainingManager())
            {
                var lsttrainingmanager = db.TrainingManagers.ToList<TrainingManager>();
                return View(lsttrainingmanager);
            }
            else
                return View("ErrorFunction");
            //________________________________
            //HttpResponseMessage responseMessage = await client.GetAsync(url);
            //if (responseMessage.IsSuccessStatusCode)
            //{
            //    var responseData = responseMessage.Content.ReadAsStringAsync().Result;

            //    var usrs = JsonConvert.DeserializeObject<List<Project>>(responseData);

            //    return View(usrs);
            //}
            //return View("Error");
        }

        // GET: mvcusers/Details/5
        public async Task<ActionResult> Details(string id)
        {
            if (IsHaveReadTrainingManager())
            {
                HttpResponseMessage responseMessage = await client.GetAsync(url + "/" + id);
                if (responseMessage.IsSuccessStatusCode)
                {
                    var responseData = responseMessage.Content.ReadAsStringAsync().Result;
                    var usr = JsonConvert.DeserializeObject<TrainingManager>(responseData);
                    return View(usr);
                }
            }

            return View("ErrorFunction");
        }
        // GET: mvcusers/Create
        public ActionResult Create()
        {
            if (IsHaveCreateTrainingManager())
            {
                TrainingManager manager = new TrainingManager();
                manager.TrainingProgramCollection = db.TrainingPrograms.ToList<TrainingProgram>();
                manager.ManagerCollection = db.Managers.ToList<Manager>();
                List<Student> lststudent = new List<Student>();

                var query = from t in db.TrainingManagers
                            join p in db.TrainingPrograms on t.TrainingProgramID equals p.TrainingProgramID
                            join s in db.Students on t.StudentID equals s.StudentID
                            select s;

                var query1 = from t in db.TrainingManagers
                             join p in db.TrainingPrograms on t.TrainingProgramID equals p.TrainingProgramID
                             join s in db.Students on t.StudentID equals s.StudentID
                             where !t.IsPass
                             select s;

                var query2 = (from s in db.Students select s).Except(query);

                var query3 = query.Except(query1);

                foreach (var item in query2)
                {
                    lststudent.Add(item);
                }

                foreach (var item in query3)
                {
                    lststudent.Add(item);
                }

                manager.StudentCollection = lststudent;
                //manager.StudentCollection = db.Students.ToList<Student>();
                manager.StageCollection = db.Stages.ToList<Stage>();
                manager.InternshipCollection = db.Internships.ToList<Internship>();
                return View(manager);
            }
            else
                return View("ErrorFunction");
        }

        // POST: mvcusers/Create

        [HttpPost]
        public async Task<ActionResult> Create(TrainingManager usr)
        {
            string std = Request.Form["StudentID"].ToString();
            string mng = Request.Form["ManagerID"].ToString();
            string tp = Request.Form["TrainingProgramID"].ToString();
            string ef = "CreateTrainingProgramNotification";
            List<string> lstEmail = new List<string>();
            List<string> lstSTD = new List<string>();
            List<string> lstMNG = new List<string>();
            List<string> lstTP = new List<string>();
            List<string> lstEFS = new List<string>();
            List<string> lstEFB1 = new List<string>();
            List<string> lstEFB2 = new List<string>();
            List<string> lstEFB3 = new List<string>();
            List<string> lstEFB4 = new List<string>();
            var emailFor = from e in db.EmailTemplates where e.EmailFor == ef select e;
            foreach (var item in emailFor)
            {
                lstEFS.Add(item.Subject);
            }
            foreach (var item in emailFor)
            {
                lstEFB1.Add(item.Body1);
                lstEFB2.Add(item.Body2);
                lstEFB3.Add(item.Body3);
                lstEFB4.Add(item.Body4);
            }
            var emailStudent = from t in db.Students where t.StudentID == std select t;
            foreach (var item in emailStudent)
            {
                lstEmail.Add(item.Email);
            }
            foreach (var item in emailStudent)
            {
                lstSTD.Add(item.Name);
            }

            var emailManager = from t in db.Managers where t.ManagerID == mng select t;
            foreach (var item in emailManager)
            {
                lstEmail.Add(item.Email);
            }
            foreach (var item in emailManager)
            {
                lstMNG.Add(item.Name);
            }
            var trainingProgram = from t in db.TrainingPrograms where t.TrainingProgramID == tp select t;
            foreach (var item in trainingProgram)
            {
                lstTP.Add(item.TrainingContent);
            }
            HttpResponseMessage responseMessage = await client.PostAsJsonAsync(url, usr);
            if (responseMessage.IsSuccessStatusCode)
            {
                //Gui mail
                foreach (var Email in lstEmail)
                {
                    foreach (var tpp in lstTP)
                    {
                        foreach (var mngg in lstMNG)
                        {
                            foreach (var stdd in lstSTD)
                            {
                                foreach (var subject in lstEFS)
                                {
                                    foreach (var body1 in lstEFB1)
                                    {
                                        foreach (var body2 in lstEFB2)
                                        {
                                            foreach (var body3 in lstEFB3)
                                            {
                                                foreach (var body4 in lstEFB4)
                                                {
                                                    SendVerificationLinkEmail(Email, subject, body1 + tpp + body2 + stdd + body3 + mngg + body4 + DateTime.Now.ToString(), tpp, mngg, stdd, ef);
                                                    foreach (var Emaill in db.SuperManagers.Select(e => e.Email).ToList())
                                                    {
                                                        SendVerificationLinkEmail(Emaill, subject, body1 + tpp + body2 + stdd + body3 + mngg + body4 + DateTime.Now.ToString(), tpp, mngg, stdd, ef);

QLThucTap_INFOdation.App/Areas/Admin/Views/TrainingManager/Create.cshtml
@model Repository.Models.TrainingManager

@{
    /**/

    ViewBag.Title = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_Layout1.cshtml";
}
@Html.AntiForgeryToken()
<!-- Content Header (Page header) -->
<section class="content-header">
    <h1>
        Training Managers
    </h1>
</section>
<!-- Main content -->
<section class="content container-fluid">
    <!-- Horizontal Form -->
    <div class="box box-info">
        <div class="box-header with-border">
            <h3 class="box-title">Add Training Manager</h3>
        </div>
        <!-- /.box-header -->
        <!-- form start -->
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <form class="form-horizontal" method="post" action="Create">
            <div class="box-body">

                <div class="form-group">
                    @Html.LabelFor(model => model.InternshipID, "InternshipID", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DropDownListFor(m => m.InternshipID, new SelectList(Model.InternshipCollection, "InternshipID", "InternshipName"), "-Choose One-", new { required = "required" })
                        @Html.ValidationMessageFor(model => model.InternshipID, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.ManagerID, "ManagerID", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DropDownListFor(m => m.ManagerID, new SelectList(Model.ManagerCollection, "ManagerID", "Name"), "-Choose One-", new { required = "required" })
                        @Html.ValidationMessageFor(model => model.ManagerID, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.StudentID, "StudentID", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DropDownListFor(m => m.StudentID, new SelectList(Model.StudentCollection, "StudentID", "Name"), "-Choose One-", new { required = "required" })
                        @Html.ValidationMessageFor(model => model.StudentID, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.StageID, "StageID", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DropDownListFor(m => m.StageID, new SelectList(Model.StageCollection, "StageID", "StageContent"), "-Choose One-", new { required = "required" })
                        @Html.ValidationMessageFor(model => model.StageID, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.TrainingProgramID, "TrainingProgramID", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DropDownListFor(m => m.TrainingProgramID, new SelectList(Model.TrainingProgramCollection, "TrainingProgramID", "TrainingContent"), "-Choose One-", new { required = "required" })
                        @Html.ValidationMessageFor(model => model.TrainingProgramID, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.AssertmentContent, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.AssertmentContent, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.AssertmentContent, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
            <!-- /.box-body -->
            <div class="box-footer">
                <button type="submit" class="btn btn-info pull-right">Create</button>
            </div>
            <div>
                @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-info", onclick = "JavascriptFunction();" })
            </div>
            <!-- /.box-footer -->
        </form>
    </div>
    <!-- /.box -->
</section>
<div id="divLoading" style="margin: 0px; padding: 0px; position: fixed; right: 0px;
    top: 0px; width: 100%; height: 100%; background-color: #666666; z-index: 30001;
    opacity: .8; filter: alpha(opacity=70);display:none">
    <p style="position: absolute; top: 50%; left: 50%; color: White;">
        <img src="~/img/ajax-loader (1).gif"><br />Please Wait...
    </p>
</div>

<script type="text/javascript" language="javascript">
    function JavascriptFunction() {
        var url = '@Url.Action("Create", "TrainingManager")';
        $("#divLoading").show();
        $.post(url, null,
                function (data) {
                    $("#PID")[0].innerHTML = data;
                    $("#divLoading").hide();
                });
    }
</script>

QLThucTap_INFOdation.App/Areas/Admin/Views/TrainingManager/Delete.cshtml
@model Repository.Models.TrainingManager

@{
    /**/

    ViewBag.Title = "Delete";
    Layout = "~/Areas/Admin/Views/Shared/_Layout1.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>TrainingManager</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Internship.InternshipName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Internship.InternshipName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Manager.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Manager.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Stage.StageContent)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Stage.StageContent)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Student.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Student.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TrainingProgram.TrainingContent)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TrainingProgram.TrainingContent)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AssertmentContent)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AssertmentContent)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsPass)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsPass)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DateCreated)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateCreated)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastUpdated)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastUpdated)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input onclick="JavascriptFunction();" type="submit" value="Delete" class="btn btn-danger" /> |
            @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-info", onclick = "JavascriptFunction();" })
        </div>
    }
</div>
<div id="divLoading" style="margin: 0px; padding: 0px; position: fixed; right: 0px;
    top: 0px; width: 100%; height: 100%; background-color: #666666; z-index: 30001;
    opacity: .8; filter: alpha(opacity=70);display:none">
    <p style="position: absolute; top: 50%; left: 50%; color: White;">
        <img src="~/img/ajax-loader (1).gif"><br />Please Wait...
    </p>
</div>

<script type="text/javascript" language="javascript">
    function JavascriptFunction() {
        var url = '@Url.Action("Delete", "TrainingManager")';
        $("#divLoading").show();
        $.post(url, null,
                function (data) {
                    $("#PID")[0].innerHTML = data;
                    $("#divLoading").hide();
                });
    }
</script>

QLThucTap_INFOdation.App/Areas/Admin/Views/TrainingManager/Details.cshtml
@model Repository.Models.TrainingManager

@{
    /**/

    ViewBag.Title = "Details";
    Layout = "~/Areas/Admin/Views/Shared/_Layout1.cshtml";
}


<h2>Details</h2>

<div>
    <h4>TrainingManager</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Internship.InternshipName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Internship.InternshipName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Manager.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Manager.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Stage.StageContent)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Stage.StageContent)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Student.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Student.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TrainingProgram.TrainingContent)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TrainingProgram.TrainingContent)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AssertmentContent)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AssertmentContent)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsPass)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsPass)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DateCreated)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateCreated)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastUpdated)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastUpdated)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.TrainingManagerID }, new { @class = "btn btn-info", onclick = "JavascriptFunction();" }) |
    @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-info", onclick = "JavascriptFunction();" })
</p>
<div id="divLoading" style="margin: 0px; padding: 0px; position: fixed; right: 0px;
    top: 0px; width: 100%; height: 100%; background-color: #666666; z-index: 30001;
    opacity: .8; filter: alpha(opacity=70);display:none">
    <p style="position: absolute; top: 50%; left: 50%; color: White;">
        <img src="~/img/ajax-loader (1).gif"><br />Please Wait...
    </p>
</div>

<script type="text/javascript" language="javascript">
    function JavascriptFunction() {
        var url = '@Url.Action("Details", "TrainingManager")';
        $("#divLoading").show();
        $.post(url, null,
                function (data) {
                    $("#PID")[0].innerHTML = data;
                    $("#divLoading").hide();
                });
    }
</script>

QLThucTap_INFOdation.App/Areas/Admin/Views/TrainingManager/Index.cshtml
@model IEnumerable<Repository.Models.TrainingManager>

@{
    /**/

    ViewBag.Title = "List of Training Managers";
    Layout = "~/Areas/Admin/Views/Shared/_Layout1.cshtml";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create", null, new { @class = "btn btn-info", onclick = "JavascriptFunction();" })
</p>
<table id="trainingmanager" class="tableStyle1">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Internship.InternshipName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Manager.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Stage.StageContent)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Student.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TrainingProgram.TrainingContent)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.AssertmentContent)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.IsPass)
            </th>
            <th></th>
        </tr>
    </thead>


    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Internship.InternshipName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Manager.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Stage.StageContent)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Student.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TrainingProgram.TrainingContent)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AssertmentContent)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IsPass)
            </td>
            <td>
                @Html.ActionLink(" ", "Edit", new { id = item.TrainingManagerID }, new { @class = "glyphicon glyphicon-edit", onclick = "JavascriptFunction();" })<br />@Html.ActionLink(" ", "Details", new { id = item.TrainingManagerID }, new { @class = "glyphicon glyphicon-eye-open", onclick = "JavascriptFunction();" })<br />@Html.ActionLink(" ", "Delete", new { id = item.TrainingManagerID }, new { @class = "glyphicon glyphicon-trash", onclick = "JavascriptFunction();" })
            </td>
        </tr>
    }

</table>


<link href="/Content/DataTables/css/jquery.dataTables.min.css" rel="stylesheet" />

@section scripts
{
    <script src="/Scripts/DataTables/jquery.dataTables.min.js"></script>
    <script>
        $(document).ready(function () {
            $("#trainingmanager").DataTable();            
        });
    </script>
    <style>
        td.highlight1 {
            background-color: #B961C3 !important;
        }

        .tableStyle1 {
            font-family: "Trebuchet MS", Arial, Helvetica, sans-serif;
            border-collapse: collapse;
            width: auto;
        }
            /*Style for Table Head - TH*/
            .tableStyle1 th {
                text-align: left;
                background-color: #8b1dba;
                color: #fff;
                text-align: left;
                padding: 25px;
            }
            /*TD and TH Style*/
            .tableStyle1 td, .tableStyle1 th {
                border: 1px solid #dedede; /*Border color*/
                padding: 15px;
            }
            /*Table Even Rows Styles*/
            .tableStyle1 tr:nth-child(even) {
                background-color: #EFF1F1;
            }
            /*Table ODD Rows Styles*/
            .tableStyle1 tr:nth-child(odd) {
                background-color: #E3EDED;
            }
            /*Table Row HOver Style*/
            .tableStyle1 tr:hover {
                background-color: #B961C3;
            }
    </style>
    <script>
        $(document).ready(function () {
            var table = $('#trainingmanager').DataTable();

            $('#trainingmanager tbody')
                .on('mouseenter', 'td', function () {
                    var colIdx = table.cell(this).index().column;

                    $(table.cells().nodes()).removeClass('highlight');
                    $(table.column(colIdx).nodes()).addClass('highlight');
                });
        });
    </script>
    <div id="divLoading" style="margin: 0px; padding: 0px; position: fixed; right: 0px;
    top: 0px; width: 100%; height: 100%; background-color: #666666; z-index: 30001;
    opacity: .8; filter: alpha(opacity=70);display:none">
        <p style="position: absolute; top: 50%; left: 50%; color: White;">
            <img src="~/img/ajax-loader (1).gif"><br/>Please Wait...
        </p>
    </div>

    <script type="text/javascript" language="javascript">
    function JavascriptFunction() {
        var url = '@Url.Action("Index", "TrainingManager")';
        $("#divLoading").show();
        $.post(url, null,
                function (data) {
                    $("#PID")[0].innerHTML = data;
                    $("#divLoading").hide();
                });
    }
    </script>
}