QLThucTap_INFOdation.App/Areas/Admin/Controllers/GUIs/ProjectInternManagersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using Newtonsoft.Json;
using PagedList;
using Repository.DAL;
using Repository.Models;
using QLThucTap_INFOdation.BusinessLogic.IService;
using QLThucTap_INFOdation.BusinessLogic.Service;
using System.Net.Mail;
using System.Net;

namespace QLThucTap_INFOdation.App.Areas.Admin.Controllers.GUIs
{
    public class ProjectInternManagersController : Controller
    {
        // GET: ManagerMVC        
        private readonly IUserPermissionService _userpermission;
        private InternContext db = new InternContext();
        string url = "http://localhost:54224/api/projectinternmanagerapi";
        HttpClient client;
        public ProjectInternManagersController()
        {
            _userpermission = new UserPermissionService();
            client = new HttpClient();
            client.BaseAddress = new Uri(url);
            client.DefaultRequestHeaders.Accept.Clear();
            client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
        }

        private bool IsHaveCreateProjectInternManager()
        {
            var findper = _userpermission.GetUserPermissionByUsername(Session["Username"].ToString());
            if (findper.Contains("Create Project Intern Manager") || findper.Contains("Full All Access") || findper.Contains("Full On Project Intern Manager"))
            {
                return true;
            }
            return false;
        }
        private bool IsHaveUpdateProjectInternManager()
        {
            var findper = _userpermission.GetUserPermissionByUsername(Session["Username"].ToString());
            if (findper.Contains("Update Project Intern Manager") || findper.Contains("Full All Access") || findper.Contains("Full On Project Intern Manager"))
            {
                return true;
            }
            return false;
        }
        private bool IsHaveReadProjectInternManager()
        {
            var findper = _userpermission.GetUserPermissionByUsername(Session["Username"].ToString());
            if (findper.Contains("Read Project Intern Manager") || findper.Contains("Full All Access") || findper.Contains("Full On Project Intern Manager"))
            {
                return true;
            }
            return false;
        }
        private bool IsHaveDeleteProjectInternManager()
        {
            var findper = _userpermission.GetUserPermissionByUsername(Session["Username"].ToString());
            if (findper.Contains("Delete Project Intern Manager") || findper.Contains("Full All Access") || findper.Contains("Full On Project Intern Manager"))
            {
                return true;
            }
            return false;
        }

        // GET: mvcusers
        //public async Task<ActionResult> Index()
        public ActionResult Index()
        {
            if (IsHaveReadProjectInternManager())
            {
                var lstprojectinternmanager = db.ProjectInternManagers.ToList<ProjectInternManager>();
                return View(lstprojectinternmanager);
            }
            else
                return View("ErrorFunction");
        }

        // GET: mvcusers/Details/5
        public async Task<ActionResult> Details(string id)
        {
            if (IsHaveReadProjectInternManager())
            {
                HttpResponseMessage responseMessage = await client.GetAsync(url + "/" + id);
                if (responseMessage.IsSuccessStatusCode)
                {
                    var responseData = responseMessage.Content.ReadAsStringAsync().Result;
                    var usr = JsonConvert.DeserializeObject<ProjectInternManager>(responseData);
                    return View(usr);
                }
            }

            return View("ErrorFunction");
        }
        // GET: mvcusers/Create
        public ActionResult Create()
        {
            if (IsHaveCreateProjectInternManager())
            {
                ProjectInternManager manager = new ProjectInternManager();
                manager.ProjectInternCollection = db.ProjectInterns.ToList<ProjectIntern>();
                manager.ManagerCollection = db.Managers.ToList<Manager>();
                List<Student> lststudent = new List<Student>();

                var s = from st in db.Students where st.ProgressID == "PROGRESS_001" select st;

                var query = from t in db.ProjectInternManagers
                            join p in db.ProjectInterns on t.ProjectInternID equals p.ProjectInternID
                            join std in db.Students on t.StudentID equals std.StudentID
                            select std;

                var query1 = from t in db.ProjectInternManagers
                             join p in db.ProjectInterns on t.ProjectInternID equals p.ProjectInternID
                             join std in db.Students on t.StudentID equals std.StudentID
                             where !t.IsPass
                             select std;

                var query2 = s.Except(query);

                var query3 = query.Except(query1);

                foreach (var item in query2)
                {
                    lststudent.Add(item);
                }

                foreach (var item in query3)
                {
                    lststudent.Add(item);
                }

                manager.StudentCollection = lststudent;
                manager.InternshipCollection = db.Internships.ToList<Internship>();
                return View(manager);
            }
            else
                return View("ErrorFunction");

        }

        // POST: mvcusers/Create

        [HttpPost]
        public async Task<ActionResult> Create(ProjectInternManager usr)
        {
            string ef = "CreateProjectInternNotification";
            string std = Request.Form["StudentID"].ToString();
            string mng = Request.Form["ManagerID"].ToString();
            string pi = Request.Form["ProjectInternID"].ToString();
            List<string> lstEmail = new List<string>();
            List<string> lstSTD = new List<string>();
            List<string> lstMNG = new List<string>();
            List<string> lstPI = new List<string>();
            List<string> lstEFS = new List<string>();
            List<string> lstEFB1 = new List<string>();
            List<string> lstEFB2 = new List<string>();
            List<string> lstEFB3 = new List<string>();
            List<string> lstEFB4 = new List<string>();
            var emailFor = from e in db.EmailTemplates where e.EmailFor == ef select e;
            foreach (var item in emailFor)
            {
                lstEFS.Add(item.Subject);
            }
            foreach (var item in emailFor)
            {
                lstEFB1.Add(item.Body1);
                lstEFB2.Add(item.Body2);
                lstEFB3.Add(item.Body3);
                lstEFB4.Add(item.Body4);
            }
            var emailStudent = from t in db.Students where t.StudentID == std select t;
            foreach (var item in emailStudent)
            {
                lstEmail.Add(item.Email);
            }
            foreach (var item in emailStudent)
            {
                lstSTD.Add(item.Name);
            }

            var emailManager = from t in db.Managers where t.ManagerID == mng select t;
            foreach (var item in emailManager)
            {
                lstEmail.Add(item.Email);
            }
            foreach (var item in emailManager)
            {
                lstMNG.Add(item.Name);
            }
            var projectIntern = from t in db.ProjectInterns where t.ProjectInternID == pi select t;
            foreach (var item in projectIntern)
            {
                lstPI.Add(item.ProjectInternName);
            }
            HttpResponseMessage responseMessage = await client.PostAsJsonAsync(url, usr);
            if (responseMessage.IsSuccessStatusCode)
            {
                //Gui mail
                //var responseData = responseMessage.Content.ReadAsStringAsync().Result;
                foreach (var Email in lstEmail)
                {
                    foreach (var pii in lstPI)
                    {
                        foreach (var mngg in lstMNG)
                        {
                            foreach (var stdd in lstSTD)
                            {
                                foreach (var subject in lstEFS)
                                {
                                    foreach (var body1 in lstEFB1)
                                    {
                                        foreach (var body2 in lstEFB2)
                                        {
                                            foreach (var body3 in lstEFB3)
                                            {
                                                foreach (var body4 in lstEFB4)
                                                {
                                                    SendVerificationLinkEmail(Email, subject, body1 + pii + body2 + stdd + body3 + mngg + body4 + DateTime.Now.ToString(), ef);
                                                    foreach (var Emaill in db.SuperManagers.Select(e => e.Email).ToList())
                                                    {
                                                        SendVerificationLinkEmail(Emaill, subject, body1 + pii + body2 + stdd + body3 + mngg + body4 + DateTime.Now.ToString(), ef);
                                                    }
                                                }
                                            }
                                        }

                                    }
                                }
                            }
                        }
                    }
                }

QLThucTap_INFOdation.App/Areas/Admin/Views/ProjectInternManagers/Create.cshtml
﻿@model Repository.Models.ProjectInternManager

@{
    /**/

    ViewBag.Title = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_Layout1.cshtml";
}
@Html.AntiForgeryToken()
<!-- Content Header (Page header) -->
<section class="content-header">
    <h1>
        Project Intern Managers
    </h1>
</section>
<!-- Main content -->
<section class="content container-fluid">
    <!-- Horizontal Form -->
    <div class="box box-info">
        <div class="box-header with-border">
            <h3 class="box-title">Add Project Intern Manager</h3>
        </div>
        <!-- /.box-header -->
        <!-- form start -->
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <form class="form-horizontal" method="post" action="Create">
            <div class="box-body">                

                <div class="form-group">
                    @Html.LabelFor(model => model.ProjectInternID, "Project Intern ID", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DropDownListFor(m => m.ProjectInternID, new SelectList(Model.ProjectInternCollection, "ProjectInternID", "ProjectInternName"), "-Choose One-", new { required = "required" })
                        @Html.ValidationMessageFor(model => model.ProjectInternID, "", new { @class = "text-danger" })

                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.ManagerID, "ManagerID", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DropDownListFor(m => m.ManagerID, new SelectList(Model.ManagerCollection, "ManagerID", "Name"), "-Choose One-", new { required = "required" })
                        @Html.ValidationMessageFor(model => model.ManagerID, "", new { @class = "text-danger" })
                    </div>
                </div>



                <div class="form-group">
                    @Html.LabelFor(model => model.StudentID, "StudentID", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DropDownListFor(m => m.StudentID, new SelectList(Model.StudentCollection, "StudentID", "Name"), "-Choose One-", new { required = "required" })
                        @Html.ValidationMessageFor(model => model.StudentID, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.InternshipID, "InternshipID", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DropDownListFor(m => m.InternshipID, new SelectList(Model.InternshipCollection, "InternshipID", "InternshipName"), "-Choose One-", new { required = "required" })
                        @Html.ValidationMessageFor(model => model.InternshipID, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
            <!-- /.box-body -->
            <div class="box-footer">
                <button type="submit" class="btn btn-info pull-right">Create</button>
            </div>
            <div>
                @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-info" })
            </div>
            <!-- /.box-footer -->
        </form>
    </div>
    <!-- /.box -->
</section>

QLThucTap_INFOdation.App/Areas/Admin/Views/ProjectInternManagers/Delete.cshtml
@model Repository.Models.ProjectInternManager

@{
    /**/

    ViewBag.Title = "Delete";
    Layout = "~/Areas/Admin/Views/Shared/_Layout1.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>ProjectInternManager</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Internship.InternshipName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Internship.InternshipName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Manager.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Manager.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ProjectIntern.ProjectInternName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProjectIntern.ProjectInternName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Student.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Student.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DateCreated)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateCreated)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastUpdated)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastUpdated)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-danger" /> |
            @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-info" })
        </div>
    }
</div>

QLThucTap_INFOdation.App/Areas/Admin/Views/ProjectInternManagers/Details.cshtml
@model Repository.Models.ProjectInternManager

@{
    /**/

    ViewBag.Title = "Details";
    Layout = "~/Areas/Admin/Views/Shared/_Layout1.cshtml";
}

<h2>Details</h2>

<div>
    <h4>ProjectInternManager</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Internship.InternshipName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Internship.InternshipName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Manager.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Manager.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ProjectIntern.ProjectInternName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProjectIntern.ProjectInternName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Student.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Student.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsPass)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsPass)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DateCreated)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateCreated)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastUpdated)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastUpdated)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ProjectInternManagerID }, new { @class = "btn btn-info" }) |
    @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-info" })
</p>

QLThucTap_INFOdation.App/Areas/Admin/Views/ProjectInternManagers/Edit.cshtml
@model Repository.Models.ProjectInternManager

@{
    /**/

    ViewBag.Title = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_Layout1.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>ProjectInternManager</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ProjectInternManagerID)

        <div class="form-group">
            @Html.LabelFor(model => model.ProjectInternID, "ProjectIntern ID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(m => m.ProjectInternID, new SelectList(Model.ProjectInternCollection, "ProjectInternID", "ProjectInternName"), "-Choose One-", new { required = "required" })
                @Html.ValidationMessageFor(model => model.ProjectInternID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ManagerID, "ManagerID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(m => m.ManagerID, new SelectList(Model.ManagerCollection, "ManagerID", "Name"), "-Choose One-", new { required = "required" })
                @Html.ValidationMessageFor(model => model.ManagerID, "", new { @class = "text-danger" })
            </div>
        </div>



        <div class="form-group">
            @Html.LabelFor(model => model.StudentID, "StudentID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(m => m.StudentID, new SelectList(Model.StudentCollection, "StudentID", "Name"), "-Choose One-", new { required = "required" })
                @Html.ValidationMessageFor(model => model.StudentID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.InternshipID, "InternshipID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(m => m.InternshipID, new SelectList(Model.InternshipCollection, "InternshipID", "InternshipName"), "-Choose One-", new { required = "required" })
                @Html.ValidationMessageFor(model => model.InternshipID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IsPass, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.IsPass)
                    @Html.ValidationMessageFor(model => model.IsPass, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>


        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-info" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-info" })
</div>

QLThucTap_INFOdation.App/Areas/Admin/Views/ProjectInternManagers/Index.cshtml
@model IEnumerable<Repository.Models.ProjectInternManager>

@{

    ViewBag.Title = "List of Project Intern Managers";
    Layout = "~/Areas/Admin/Views/Shared/_Layout1.cshtml";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create", null, new { @class = "btn btn-info" })
</p>
<table id="projectinternmanager" class="tableStyle1">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Internship.InternshipName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Manager.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ProjectIntern.ProjectInternName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Student.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.IsPass)
            </th>
            <th></th>
        </tr>
    </thead>


    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Internship.InternshipName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Manager.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ProjectIntern.ProjectInternName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Student.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IsPass)
            </td>
            <td>
                @Html.ActionLink(" ", "Edit", new { id = item.ProjectInternManagerID }, new { @class = "glyphicon glyphicon-edit", onclick = "JavascriptFunction();" })<br />@Html.ActionLink(" ", "Details", new { id = item.ProjectInternManagerID }, new { @class = "glyphicon glyphicon-eye-open", onclick = "JavascriptFunction();" })<br />@Html.ActionLink(" ", "Delete", new { id = item.ProjectInternManagerID }, new { @class = "glyphicon glyphicon-trash", onclick = "JavascriptFunction();" })
            </td>
        </tr>
    }

</table>

<link href="/Content/DataTables/css/jquery.dataTables.min.css" rel="stylesheet" />

@section scripts
{
    <script src="/Scripts/DataTables/jquery.dataTables.min.js"></script>
    <script>
        $(document).ready(function () {
            $("#projectinternmanager").DataTable();            
        });
    </script>
    <style>
        td.highlight1 {
            background-color: #B961C3 !important;
        }

        .tableStyle1 {
            font-family: "Trebuchet MS", Arial, Helvetica, sans-serif;
            border-collapse: collapse;
            width: auto;
        }
            /*Style for Table Head - TH*/
            .tableStyle1 th {
                text-align: left;
                background-color: #8b1dba;
                color: #fff;
                text-align: left;
                padding: 25px;
            }
            /*TD and TH Style*/
            .tableStyle1 td, .tableStyle1 th {
                border: 1px solid #dedede; /*Border color*/
                padding: 15px;
            }
            /*Table Even Rows Styles*/
            .tableStyle1 tr:nth-child(even) {
                background-color: #EFF1F1;
            }
            /*Table ODD Rows Styles*/
            .tableStyle1 tr:nth-child(odd) {
                background-color: #E3EDED;
            }
            /*Table Row HOver Style*/
            .tableStyle1 tr:hover {
                background-color: #B961C3;
            }
    </style>
    <script>
        $(document).ready(function () {
            var table = $('#projectinternmanager').DataTable();

            $('#projectinternmanager tbody')
                .on('mouseenter', 'td', function () {
                    var colIdx = table.cell(this).index().column;

                    $(table.cells().nodes()).removeClass('highlight');
                    $(table.column(colIdx).nodes()).addClass('highlight');
                });
        });
    </script>
    <div id="divLoading" style="margin: 0px; padding: 0px; position: fixed; right: 0px;
    top: 0px; width: 100%; height: 100%; background-color: #666666; z-index: 30001;
    opacity: .8; filter: alpha(opacity=70);display:none">
        <p style="position: absolute; top: 50%; left: 50%; color: White;">
            <img src="~/img/ajax-loader (1).gif"><br/>Please Wait...
        </p>
    </div>

    <script type="text/javascript" language="javascript">
    function JavascriptFunction() {
        var url = '@Url.Action("Index", "ProjectInternManagers")';
        $("#divLoading").show();
        $.post(url, null,
                function (data) {
                    $("#PID")[0].innerHTML = data;
                    $("#divLoading").hide();
                });
    }
    </script>
}